#!/bin/sh

wget ftp://ftp.perforce.com/perforce/r20.1/bin.linux26x86_64/p4d
chmod +x p4d
sudo mv p4d /usr/local/bin
sudo adduser perforce
sudo mkdir /mnt/perforce/root
sudo chown /mnt/perforce/root
sudo mkdir /var/log/perforce
sudo chown perforce /var/log/perforce
sudo apt-get install daemon
cd /etc/init.d
wget https://raw.githubusercontent.com/proguerammer/linux-perforce-installer/master/p4dservice
chmod +x /etc/init.d/p4dservice
sudo update-rc.d p4dservice defaults
sudo reboot
